### ISSUE TITLE
avoid setTemplateOverride

### ISSUE THREAD

**Issue by Busfreak** [gusthoff/kanboard-plugin-column-group#2]
Hello Gustavo,
really nice!

I will give you some thoughts, if you like.

Instead of overriding board/table_column you should give Frédéric a PR introducing your hook "template:board:table:column:before-header-row" to the core.

**Comment by gusthoff** [comment]
Yes, I totally agree with you! Actually, the idea behind that part of the plug-in was to create an initial version that just works without requiring changes in Kanboard, but also requires minimal changes when that hook is implemented.

**Comment by gusthoff** [comment]
Sent pull request: https://github.com/kanboard/kanboard/pull/3075

**Comment by gusthoff** [comment]
Solved with commit 58c1c32d3c6a03a0c0b89e0eef4afd52f5291e62.
