### ISSUE TITLE
Add new column group for board manager

### ISSUE THREAD

**Issue by Busfreak** [gusthoff/kanboard-plugin-column-group#4]
Maybe it would be more handy if the board manager can add new column groups, not only the admin.

**Comment by gusthoff** [comment]
Well, the manager role does not allow for editing global tags, either. The concept implemented in this plug-in is that column groups are global across projects. The idea is that a small set of global columns should be sufficient to group columns in various projects. But maybe this is only useful for my use-case. ;-)

**Comment by gusthoff** [comment]
I decided to implement this, even though I won't be using this feature on my personal Kanboard server. Have fun! :-)

**Comment by Busfreak** [comment]
->Have fun! :-)

I will! THX!
