### ISSUE TITLE
Remove column group code

### ISSUE THREAD

**Issue by Busfreak** [gusthoff/kanboard-plugin-column-group#5]
If you edit a column, the first groupcode is set for column group code. You can't remove it.

**Comment by Busfreak** [comment]
Maybe you could use "`id` INT NOT NULL AUTO_INCREMENT" instead of "code VARCHAR(30) NOT NULL" in table column_groups, use "0" for "nothing set", hide the column group code in the templates and use title instead.
Then you can change "ALTER TABLE columns ADD COLUMN column_group_code VARCHAR(30)" to "ALTER TABLE columns ADD COLUMN column_group_id INT DEFAULT '0'" and the keys accordingly.

**Comment by gusthoff** [comment]
I'm sorry, but I don't understand it. What exactly are you not able to remove? Are you saying that you cannot remove a column from a column group once it is added (to the group)? Are you referring to this page?

http://127.0.0.1/kanboard/?controller=ProjectColumnGroupController&action=index&plugin=ColumnGroup&project_id=1

Could you please write some details about the issue --- like steps to reproduce it, database used, and so on?

**Comment by Busfreak** [comment]
Sorry, too many thoughts at once :smile: 

Yes, I am referring to ProjectColumnGroupController->index.
There is always a group set and you can't remove ist:
![image1](https://cloud.githubusercontent.com/assets/12938119/20003884/3a2a32a0-a289-11e6-8529-eba10ed9a742.jpg)

**Comment by Busfreak** [comment]
The thoughts about the database schema are the following:
If you have a dropdown select field with items from the database and the ability to set its value to "empty", you have to add an "empty" item. There is one easy way doing it. Instead of using a varchar for the index, you use a numerical index, starting from >0, set the default value (column_group_code in columns) to 0 (meaning nothing set) and you are done.
Moreover you don't need to display the index (you called it code) in the select field or in any template, for this you have the title field.

For example have a look at controller=TaskModificationController&action=edit field category.
The category items are set with categoryModel->getList.

I really love your approach!!

**Comment by gusthoff** [comment]
You can remove the association between a column and a column group — in other words, remove a column from a column group — by clicking on "Remove". You can find this option on the same menu where you find the "Edit" option. Clicking on "Yes" (in the pop-up window) should remove the association. Please let me know if this is not working for you.

Of course, as you're saying, instead of having a "Remove" option, an "empty item" on the drop-down menu would have the same effect. Maybe that would be more intuitive...

**Comment by gusthoff** [comment]
Ok, I've just made the following changes:
- Renamed "Remove" to "Remove from group"
- Added "empty item" to the drop-down menu.

Now, there are two options to remove a column from a column group. Maybe having just one option is better, but that can be changed later.
