### ISSUE TITLE
installing this plugin is breaking 'Add task' (+ button)

### ISSUE THREAD

**Issue by 2Belette** [gusthoff/kanboard-plugin-column-group#7]
Hi,
Many thanks for this plugin, exactly what I missed.
The only (huge) problem is that it breaks the new task windows, see attached: 
any idea?

![2017-02-22-11 25 56](https://cloud.githubusercontent.com/assets/2325706/23207532/e2e261ec-f8f1-11e6-98db-97d170b67c0d.png)

    Application version: master
    PHP version: 7.0.13
    PHP SAPI: apache2handler
    OS version: Linux 4.8.10-gnu-1
    Database driver: sqlite
    Database version: 3.15.1
    Browser: Mozilla/5.0 (Windows NT 6.1; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by gusthoff** [comment]
Fixed on v0.2.0: https://github.com/gusthoff/kanboard-plugin-column-group/releases/tag/0.2.0

**Comment by 2Belette** [comment]
Very good working now :)
Your plugin should be included into kanboard as a feature!
