### ISSUE TITLE
How to use plugin?

### ISSUE THREAD

**Issue by kf0mlb** [gusthoff/kanboard-plugin-column-group#9]
I've looked over the README, I've installed the plugin, it shows up, but how do I use/implement it?

**Comment by firedrow** [comment]
Found it under System Settings, I was looking for settings within the Project.

**Comment by kf0mlb** [comment]
Found the settings under System, not Project settings.  But I can't figure out how to use this.  I've added one group code, InProgress, but then what?  Making a column named InProgress:Something or InProgress Anything didn't make a group.

Now I've found the ColumnGroup stuff per project, added some columns to a column group code, and I still see individual columns.
